# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a52f8b27ac053742dcf69e5e697008f300b0f84453369d1f4c7aec56d0c8632a28394db7eda1355c720a5d3fa742e72bb6dee0b96782bea1c7ecf82c727b760b

test:
  secret_key_base: 379cba939585b5f5ef6f39b22596d872dcbfd5d82396f911eb0070b49ac3fedf08893b3e4a5d2a56ad332b04bf0a903de616be751c5f9777074d4e58c7504e4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
